
print("Mauuuuuido!")
raise Exception("El Hombre de las matematicas!!!")
